#### 1. Importando a biblioteca
A convenção universal da comunidade é importar o Pandas com o alias pd

In [4]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kieran\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kieran\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\kieran\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -------------------------------------- - 9.4/9.7 MB 53.3 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 43.3 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import numpy as np # Frewquentemente usado junto com pandas

#### 2. Estrutura de dados: Series e DataFrames
* Series: É uma matriz unidimensional com rótulos(índices) - pode ser vista como uma única coluna de uma tabela
* DataFrames: É uma estrutura bidimensional (linhas e colunas), como uma planilha completa - é essencialmente um conjunto de Series

In [6]:
# Criando uma Series
notas = pd.Series([8.5, 9.0, 7.5, 10], index=['Aluno A', 'Aluno B', 'Aluno C', 'Aluno D'])
print('Exemplo de Series: \n', notas, '\n')

Exemplo de Series:
 Aluno A     8.5
Aluno B     9.0
Aluno C     7.5
Aluno D    10.0
dtype: float64

In [8]:
# Criando um DataFrame a partir de um dicionário (útil para testes locais)

dados_turma = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'Idade': [20, 22, 23, 21],
    'Nota_Final': [8.5, 9.0, 7.5, 6.5],
    'Aprovado': [True, True, True, False]
}

df = pd.DataFrame(dados_turma)
print('Exemplo de DataFrame:')
display(df) # O display renderiza uma tabela mais bonita no Jupyter do que o 'print'

Exemplo de DataFrame:

     Nome  Idade  Nota_Final  Aprovado
0     Ana     20         8.5      True
1   Bruno     22         9.0      True
2  Carlos     23         7.5      True
3   Diana     21         6.5     False

#### 3. Lendo Dados de Arquivos Externos (CSV)
Na prática real de análise, nós raramente geramos os dados manualmente no código. O fluxo normal é ler os dados direatamente de arquivos, sendo o formato CSV o mais comum

In [9]:
# O comando abaixo é o padrão
#df_csv = pd.read_csv('caminho')

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = pd.read_csv(url)
print('Dados carregados com sucesso!')

Dados carregados com sucesso!

In [15]:
display(df_titanic) #O display formata fora do notebook.
#Então se eu criar um modelo de ML como .py e rodar no terminal o display é bom pra isso
#É bom rodar modelos de ML assim pois o Jupyter utiliza um HTTP pra conversar com o Kernel e isso pode atrasar pra rodar

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
# head() mostra as 5 primeiras linhas do df
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
print(df_titanic.shape) # (linhas, colunas)

(891, 12)

In [24]:
df_titanic.info() #Informações gerais e tipos de dados

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

#### 5. Seleção e Filtragem de Dados
Como selecionar colunas específicas e filtrar linhas baseadas em condições

In [ ]:
#Selecionando uma coluna (retorna uma Series)
idades = df_titanic['Age']

#Selecionando múltiplas colunas (retorna um novo df)
df_reduzido = df_titanic[['Name', 'Age', 'Survived']]

#Filtragem (querying): Selecionando apenas passageiros com mais de 60 anos
passageiros_idosos = df_titanic[df_titanic['Age'] > 60]
print('Total de passageiros com mais de 60 anos:', len(passageiros_idosos))

Total de passageiros com mais de 60 anos: 22

In [29]:
#Filtragem de múltiplas condições
#Ex.: Mulheres que sobreviveram na 1° classe
filtro = (df_titanic['Sex'] == 'female') & (df_titanic['Survived'] == 1) & (df_titanic['Pclass'] == 1) #São 3 tuplas
mulheres_1a_classe = df_titanic[filtro]

print('Mulheres da 1a classe que sobreviveram', len(mulheres_1a_classe))
display(mulheres_1a_classe)

Mulheres da 1a classe que sobreviveram 91

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S